# Generated by Django 6.0.2 on 2026-02-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del curso')),
                ('descripcion', models.TextField(verbose_name='Descripción del curso')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos/', verbose_name='Imagen')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
    ]
