# Generated by Django 6.0.2 on 2026-02-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='duracion_horas',
            field=models.IntegerField(default=0, verbose_name='Duración (horas)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='modalidad',
            field=models.CharField(choices=[('EN_LINEA', 'En línea'), ('PRESENCIAL', 'Presencial')], default='EN_LINEA', max_length=20, verbose_name='Modalidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/', verbose_name='Imagen del curso'),
        ),
    ]
