# Generated by Django 6.0.2 on 2026-02-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_duracion_horas_curso_modalidad_curso_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duracion_horas',
            field=models.PositiveIntegerField(verbose_name='Duración (horas)'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='modalidad',
            field=models.CharField(choices=[('EN_LINEA', 'En línea'), ('PRESENCIAL', 'Presencial')], max_length=12, verbose_name='Modalidad'),
        ),
    ]
